# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "sprint-4-release" ]
  pull_request:
    branches: [ "sprint-4-release" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    defaults:
      run:
         working-directory:  Week-4
    runs-on:  ubuntu-latest
    permissions:
      id-token: write
      contents: read
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ap-south-1
          ## the following creates an ARN based on the values entered into github secrets 0#
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_DEV }}:role/${{ secrets.AWS_DEPLOY_ROLE_DEV }}
          role-session-name: myGitHubActions
          
      - name: NodeJS Setup
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install AWS CDK
        run: npm install -g aws-cdk
      
      - name: Install dependencies and deploy Stack
        run: | 
          ls -l
          pwd
          sudo npm install
          ls -l
          sudo npm start

        
